-- Salon POS - PostgreSQL DDL
-- Salon POS schema (BIGINT ids)
-- All primary keys and FK *Id columns are BIGINT (LONG).
-- Demo seed JSON may still use string codes in the UI; map them to BIGINT in the API layer.

BEGIN;

CREATE TABLE IF NOT EXISTS organizations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  name VARCHAR(255),
  slug VARCHAR(255),
  domain VARCHAR(255),
  website VARCHAR(255),
  "businessType" VARCHAR(255),
  "brandColor" VARCHAR(255),
  "pointsPerRupee" INTEGER,
  "rupeesPerPoint" INTEGER,
  "whatsappPhoneNumberId" VARCHAR(255),
  "whatsappBusinessAccountId" VARCHAR(255),
  "whatsappDisplayNumber" VARCHAR(255),
  "whatsappApiKey" VARCHAR(255),
  "whatsappWebhookToken" VARCHAR(255),
  "whatsappApiVersion" VARCHAR(255),
  "whatsappConnected" VARCHAR(255),
  status VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE,
  "earnUnitRupees" INTEGER,
  "pointsPerUnit" INTEGER,
  "loyaltyMinSpend" INTEGER,
  "rewardWheelWeights" TEXT,
  "rewardScratchWeights" TEXT,
  "rewardCustomerTierWeights" TEXT,
  "publicBookingShowPrizeWheel" VARCHAR(255),
  "publicBookingShowScratchCard" VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_organizations_org ON organizations ("orgId");
CREATE INDEX IF NOT EXISTS idx_organizations_loc ON organizations ("locationId");

CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  name VARCHAR(255),
  code VARCHAR(255),
  city VARCHAR(255),
  address TEXT,
  phone VARCHAR(255),
  email VARCHAR(255),
  timezone VARCHAR(255),
  status VARCHAR(255),
  lat NUMERIC,
  lng NUMERIC,
  "placeId" VARCHAR(255),
  "googleRating" INTEGER,
  "googleReviewCount" INTEGER,
  "googleSyncedAt" VARCHAR(255),
  "googleMapsUrl" VARCHAR(255),
  "googleSyncSource" VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_locations_org ON locations ("orgId");
CREATE INDEX IF NOT EXISTS idx_locations_loc ON locations ("locationId");

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  name VARCHAR(255),
  phone VARCHAR(255),
  email VARCHAR(255),
  gender VARCHAR(255),
  birthday DATE,
  anniversary DATE,
  household VARCHAR(255),
  tier VARCHAR(255),
  points INTEGER,
  "walletBalance" NUMERIC,
  outlet VARCHAR(255),
  "lastVisit" DATE,
  notes TEXT,
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE,
  "membershipId" BIGINT,
  "stampsCurrent" INTEGER,
  "totalVisits" NUMERIC,
  "referralCode" VARCHAR(255),
  "marketingConsent" VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_customers_org ON customers ("orgId");
CREATE INDEX IF NOT EXISTS idx_customers_loc ON customers ("locationId");

CREATE TABLE IF NOT EXISTS appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  "customerId" BIGINT,
  customer VARCHAR(255),
  "serviceId" BIGINT,
  service VARCHAR(255),
  "staffId" BIGINT,
  staff VARCHAR(255),
  outlet VARCHAR(255),
  date DATE,
  time TIME,
  duration INTEGER,
  status VARCHAR(255),
  source VARCHAR(255),
  notes TEXT,
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_appointments_org ON appointments ("orgId");
CREATE INDEX IF NOT EXISTS idx_appointments_loc ON appointments ("locationId");

CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  customer VARCHAR(255),
  outlet VARCHAR(255),
  date DATE,
  items TEXT,
  subtotal NUMERIC,
  discount NUMERIC,
  "gstRate" NUMERIC,
  tax NUMERIC,
  total NUMERIC,
  payment VARCHAR(255),
  status VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE,
  "customerId" BIGINT,
  "membershipId" BIGINT
);

CREATE INDEX IF NOT EXISTS idx_invoices_org ON invoices ("orgId");
CREATE INDEX IF NOT EXISTS idx_invoices_loc ON invoices ("locationId");

CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  name VARCHAR(255),
  category VARCHAR(255),
  duration INTEGER,
  price NUMERIC,
  "gstRate" NUMERIC,
  commission NUMERIC,
  outlet VARCHAR(255),
  active VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE,
  type VARCHAR(255),
  "comboItems" TEXT,
  "productNeeds" TEXT
);

CREATE INDEX IF NOT EXISTS idx_services_org ON services ("orgId");
CREATE INDEX IF NOT EXISTS idx_services_loc ON services ("locationId");

CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  name VARCHAR(255),
  category VARCHAR(255),
  brand VARCHAR(255),
  outlet VARCHAR(255),
  stock INTEGER,
  "reorderLevel" INTEGER,
  "unitCost" NUMERIC,
  "sellPrice" NUMERIC,
  batch VARCHAR(255),
  expiry DATE,
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_inventory_org ON inventory ("orgId");
CREATE INDEX IF NOT EXISTS idx_inventory_loc ON inventory ("locationId");

CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  category VARCHAR(255),
  vendor VARCHAR(255),
  outlet VARCHAR(255),
  date DATE,
  amount NUMERIC,
  payment VARCHAR(255),
  status VARCHAR(255),
  approver VARCHAR(255),
  notes TEXT,
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE,
  "skuId" BIGINT,
  sku VARCHAR(255),
  quantity INTEGER,
  "stockPosted" VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_expenses_org ON expenses ("orgId");
CREATE INDEX IF NOT EXISTS idx_expenses_loc ON expenses ("locationId");

CREATE TABLE IF NOT EXISTS staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  name VARCHAR(255),
  role VARCHAR(255),
  outlet VARCHAR(255),
  phone VARCHAR(255),
  email VARCHAR(255),
  "joinDate" DATE,
  "baseSalary" INTEGER,
  "commissionRate" NUMERIC,
  target INTEGER,
  status VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_staff_org ON staff ("orgId");
CREATE INDEX IF NOT EXISTS idx_staff_loc ON staff ("locationId");

CREATE TABLE IF NOT EXISTS shifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  date DATE,
  "startTime" TIME,
  "endTime" TIME,
  "shiftType" VARCHAR(255),
  "weeklyOff" VARCHAR(255),
  status VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE,
  "staffId" BIGINT
);

CREATE INDEX IF NOT EXISTS idx_shifts_org ON shifts ("orgId");
CREATE INDEX IF NOT EXISTS idx_shifts_loc ON shifts ("locationId");

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  date DATE,
  "checkIn" TIME,
  "checkOut" TIME,
  remarks VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE,
  "staffId" BIGINT
);

CREATE INDEX IF NOT EXISTS idx_attendance_org ON attendance ("orgId");
CREATE INDEX IF NOT EXISTS idx_attendance_loc ON attendance ("locationId");

CREATE TABLE IF NOT EXISTS leaves (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  type VARCHAR(255),
  "fromDate" DATE,
  "toDate" DATE,
  status VARCHAR(255),
  approver VARCHAR(255),
  reason VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE,
  "staffId" BIGINT,
  days INTEGER
);

CREATE INDEX IF NOT EXISTS idx_leaves_org ON leaves ("orgId");
CREATE INDEX IF NOT EXISTS idx_leaves_loc ON leaves ("locationId");

CREATE TABLE IF NOT EXISTS payroll (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  period VARCHAR(255),
  incentive NUMERIC,
  status VARCHAR(255),
  "payDate" DATE,
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE,
  "staffId" BIGINT,
  "extraDeductions" INTEGER
);

CREATE INDEX IF NOT EXISTS idx_payroll_org ON payroll ("orgId");
CREATE INDEX IF NOT EXISTS idx_payroll_loc ON payroll ("locationId");

CREATE TABLE IF NOT EXISTS commissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  type VARCHAR(255),
  "baseAmount" NUMERIC,
  rate NUMERIC,
  amount NUMERIC,
  date DATE,
  status VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE,
  "staffId" BIGINT,
  "invoiceId" BIGINT,
  "serviceId" BIGINT,
  item VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_commissions_org ON commissions ("orgId");
CREATE INDEX IF NOT EXISTS idx_commissions_loc ON commissions ("locationId");

CREATE TABLE IF NOT EXISTS feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  customer VARCHAR(255),
  invoice VARCHAR(255),
  staff VARCHAR(255),
  outlet VARCHAR(255),
  date DATE,
  rating INTEGER,
  nps INTEGER,
  channel VARCHAR(255),
  status VARCHAR(255),
  comment TEXT,
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_feedback_org ON feedback ("orgId");
CREATE INDEX IF NOT EXISTS idx_feedback_loc ON feedback ("locationId");

CREATE TABLE IF NOT EXISTS "googleReviews" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  outlet VARCHAR(255),
  author VARCHAR(255),
  rating INTEGER,
  "relativeTime" VARCHAR(255),
  date DATE,
  comment TEXT,
  source VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_googleReviews_org ON "googleReviews" ("orgId");
CREATE INDEX IF NOT EXISTS idx_googleReviews_loc ON "googleReviews" ("locationId");

CREATE TABLE IF NOT EXISTS loyalty (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  name VARCHAR(255),
  type VARCHAR(255),
  "earnRate" VARCHAR(255),
  "redeemValue" VARCHAR(255),
  tier VARCHAR(255),
  "minSpend" INTEGER,
  "expiryMonths" INTEGER,
  "qrEnabled" VARCHAR(255),
  status VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE,
  "earnUnitRupees" INTEGER,
  "pointsPerUnit" INTEGER,
  "rupeesPerPoint" INTEGER,
  "rewardDescription" TEXT,
  "stampsRequired" INTEGER,
  "spinsAllowed" VARCHAR(255),
  "requiresCheckIn" VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_loyalty_org ON loyalty ("orgId");
CREATE INDEX IF NOT EXISTS idx_loyalty_loc ON loyalty ("locationId");

CREATE TABLE IF NOT EXISTS "wheelSegments" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  "programId" BIGINT,
  label VARCHAR(255),
  "rewardTier" VARCHAR(255),
  "prizeType" VARCHAR(255),
  "prizeValue" INTEGER,
  "winWeight" NUMERIC,
  "colorHex" VARCHAR(255),
  active VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_wheelSegments_org ON "wheelSegments" ("orgId");
CREATE INDEX IF NOT EXISTS idx_wheelSegments_loc ON "wheelSegments" ("locationId");

CREATE TABLE IF NOT EXISTS "wheelSpins" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  "customerId" BIGINT,
  "programId" BIGINT,
  "segmentId" BIGINT,
  "rewardType" VARCHAR(255),
  "rewardValue" INTEGER,
  label VARCHAR(255),
  source VARCHAR(255),
  "referenceId" BIGINT,
  "checkinId" BIGINT,
  status VARCHAR(255),
  "createdAt" DATE,
  "loyaltyTransactionId" BIGINT,
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_wheelSpins_org ON "wheelSpins" ("orgId");
CREATE INDEX IF NOT EXISTS idx_wheelSpins_loc ON "wheelSpins" ("locationId");

CREATE TABLE IF NOT EXISTS "scratchPrizes" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  "programId" BIGINT,
  label VARCHAR(255),
  "rewardTier" VARCHAR(255),
  "prizeType" VARCHAR(255),
  "prizeValue" INTEGER,
  "winWeight" NUMERIC,
  "colorHex" VARCHAR(255),
  active VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_scratchPrizes_org ON "scratchPrizes" ("orgId");
CREATE INDEX IF NOT EXISTS idx_scratchPrizes_loc ON "scratchPrizes" ("locationId");

CREATE TABLE IF NOT EXISTS "scratchPlays" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  "customerId" BIGINT,
  "programId" BIGINT,
  "prizeId" BIGINT,
  "rewardType" VARCHAR(255),
  "rewardValue" INTEGER,
  label VARCHAR(255),
  source VARCHAR(255),
  "referenceId" BIGINT,
  "checkinId" BIGINT,
  status VARCHAR(255),
  "createdAt" DATE,
  "loyaltyTransactionId" BIGINT,
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_scratchPlays_org ON "scratchPlays" ("orgId");
CREATE INDEX IF NOT EXISTS idx_scratchPlays_loc ON "scratchPlays" ("locationId");

CREATE TABLE IF NOT EXISTS "qrCheckins" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  "customerId" BIGINT,
  customer VARCHAR(255),
  phone VARCHAR(255),
  "staffId" BIGINT,
  staff VARCHAR(255),
  "billAmount" NUMERIC,
  "rewardEarned" VARCHAR(255),
  verification VARCHAR(255),
  status VARCHAR(255),
  "visitAt" VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_qrCheckins_org ON "qrCheckins" ("orgId");
CREATE INDEX IF NOT EXISTS idx_qrCheckins_loc ON "qrCheckins" ("locationId");

CREATE TABLE IF NOT EXISTS "qrOffers" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  title VARCHAR(255),
  description TEXT,
  "offerType" VARCHAR(255),
  "eligibleSegment" TEXT,
  "validityStart" DATE,
  "validityEnd" DATE,
  status VARCHAR(255),
  "buyQty" INTEGER,
  "freeQty" INTEGER,
  "serviceName" VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_qrOffers_org ON "qrOffers" ("orgId");
CREATE INDEX IF NOT EXISTS idx_qrOffers_loc ON "qrOffers" ("locationId");

CREATE TABLE IF NOT EXISTS partnerships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  "partnerName" VARCHAR(255),
  status VARCHAR(255),
  "outboundOffer" VARCHAR(255),
  "inboundOffer" VARCHAR(255),
  issued INTEGER,
  redeemed INTEGER
);

CREATE INDEX IF NOT EXISTS idx_partnerships_org ON partnerships ("orgId");
CREATE INDEX IF NOT EXISTS idx_partnerships_loc ON partnerships ("locationId");

CREATE TABLE IF NOT EXISTS "qrOfferRedemptions" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  "offerId" BIGINT,
  "customerId" BIGINT,
  "checkinId" BIGINT,
  "invoiceId" BIGINT,
  status VARCHAR(255),
  "discountAmount" NUMERIC,
  "issuedAt" VARCHAR(255),
  "redeemedAt" VARCHAR(255),
  "offerTitle" VARCHAR(255),
  "offerType" VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_qrOfferRedemptions_org ON "qrOfferRedemptions" ("orgId");
CREATE INDEX IF NOT EXISTS idx_qrOfferRedemptions_loc ON "qrOfferRedemptions" ("locationId");

CREATE TABLE IF NOT EXISTS "partnerCoupons" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  "partnerId" BIGINT,
  "customerId" BIGINT,
  direction VARCHAR(255),
  offer VARCHAR(255),
  "couponCode" VARCHAR(255),
  status VARCHAR(255),
  "issuedAt" VARCHAR(255),
  "redeemedAt" VARCHAR(255),
  "invoiceId" BIGINT
);

CREATE INDEX IF NOT EXISTS idx_partnerCoupons_org ON "partnerCoupons" ("orgId");
CREATE INDEX IF NOT EXISTS idx_partnerCoupons_loc ON "partnerCoupons" ("locationId");

CREATE TABLE IF NOT EXISTS memberships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  plan VARCHAR(255),
  "startDate" VARCHAR(255),
  "endDate" VARCHAR(255),
  used INTEGER,
  status VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE,
  "planId" BIGINT,
  "customerId" BIGINT
);

CREATE INDEX IF NOT EXISTS idx_memberships_org ON memberships ("orgId");
CREATE INDEX IF NOT EXISTS idx_memberships_loc ON memberships ("locationId");

CREATE TABLE IF NOT EXISTS campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  name VARCHAR(255),
  channel VARCHAR(255),
  segment VARCHAR(255),
  audience INTEGER,
  sent INTEGER,
  opened INTEGER,
  converted INTEGER,
  budget NUMERIC,
  schedule VARCHAR(255),
  status VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_campaigns_org ON campaigns ("orgId");
CREATE INDEX IF NOT EXISTS idx_campaigns_loc ON campaigns ("locationId");

CREATE TABLE IF NOT EXISTS franchises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  name VARCHAR(255),
  type VARCHAR(255),
  city VARCHAR(255),
  owner VARCHAR(255),
  phone VARCHAR(255),
  gstin VARCHAR(255),
  royalty NUMERIC,
  "goLive" DATE,
  status VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_franchises_org ON franchises ("orgId");
CREATE INDEX IF NOT EXISTS idx_franchises_loc ON franchises ("locationId");

CREATE TABLE IF NOT EXISTS "brandApps" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  outlet VARCHAR(255),
  "appName" VARCHAR(255),
  "primaryColor" VARCHAR(255),
  "bundleId" VARCHAR(255),
  platform VARCHAR(255),
  version VARCHAR(255),
  website VARCHAR(255),
  status VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_brandApps_org ON "brandApps" ("orgId");
CREATE INDEX IF NOT EXISTS idx_brandApps_loc ON "brandApps" ("locationId");

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  name VARCHAR(255),
  code VARCHAR(255),
  description TEXT,
  "builtIn" VARCHAR(255),
  view TEXT,
  edit TEXT,
  status VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_roles_org ON roles ("orgId");
CREATE INDEX IF NOT EXISTS idx_roles_loc ON roles ("locationId");

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  name VARCHAR(255),
  email VARCHAR(255),
  role VARCHAR(255),
  outlet VARCHAR(255),
  permissions TEXT,
  "lastLogin" VARCHAR(255),
  status VARCHAR(255),
  passwordhash VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_users_org ON users ("orgId");
CREATE INDEX IF NOT EXISTS idx_users_loc ON users ("locationId");

CREATE TABLE IF NOT EXISTS "referenceValues" (
  "referenceType" VARCHAR(255),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  value VARCHAR(255),
  status VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE,
  "orgId" BIGINT NOT NULL,
  "displayOrder" INTEGER
);

CREATE INDEX IF NOT EXISTS idx_referenceValues_org ON "referenceValues" ("orgId");

CREATE TABLE IF NOT EXISTS "membershipPlans" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  name VARCHAR(255),
  price NUMERIC,
  "validityMonths" INTEGER,
  benefits TEXT,
  "includedMatch" VARCHAR(255),
  "includedLimit" INTEGER,
  "extraDiscountMatch" VARCHAR(255),
  "extraDiscountPct" NUMERIC,
  "retailDiscountPct" NUMERIC,
  status VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_membershipPlans_org ON "membershipPlans" ("orgId");
CREATE INDEX IF NOT EXISTS idx_membershipPlans_loc ON "membershipPlans" ("locationId");

CREATE TABLE IF NOT EXISTS "loyaltyTransactions" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  "customerId" BIGINT,
  "invoiceId" BIGINT,
  "programId" BIGINT,
  type VARCHAR(255),
  points INTEGER,
  source VARCHAR(255),
  "referenceId" BIGINT,
  "balanceBefore" NUMERIC,
  "balanceAfter" NUMERIC,
  reason VARCHAR(255),
  "expiresOn" DATE,
  status VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_loyaltyTransactions_org ON "loyaltyTransactions" ("orgId");
CREATE INDEX IF NOT EXISTS idx_loyaltyTransactions_loc ON "loyaltyTransactions" ("locationId");

CREATE TABLE IF NOT EXISTS "membershipUsage" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  "customerId" BIGINT,
  "membershipId" BIGINT,
  "planId" BIGINT,
  "invoiceId" BIGINT,
  "serviceId" BIGINT,
  "serviceName" VARCHAR(255),
  quantity INTEGER,
  type VARCHAR(255),
  status VARCHAR(255),
  "usedOn" DATE,
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_membershipUsage_org ON "membershipUsage" ("orgId");
CREATE INDEX IF NOT EXISTS idx_membershipUsage_loc ON "membershipUsage" ("locationId");

CREATE TABLE IF NOT EXISTS "stockMovements" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  sku VARCHAR(255),
  "skuId" BIGINT,
  "skuName" VARCHAR(255),
  "customerId" BIGINT,
  "invoiceId" BIGINT,
  "expenseId" BIGINT,
  type VARCHAR(255),
  quantity INTEGER,
  "qtyIn" INTEGER,
  "qtyOut" INTEGER,
  date DATE,
  "balanceBefore" NUMERIC,
  "balanceAfter" NUMERIC,
  reason VARCHAR(255),
  status VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_stockMovements_org ON "stockMovements" ("orgId");
CREATE INDEX IF NOT EXISTS idx_stockMovements_loc ON "stockMovements" ("locationId");

CREATE TABLE IF NOT EXISTS "serviceProducts" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  "serviceId" BIGINT,
  sku VARCHAR(255),
  "skuId" BIGINT,
  quantity INTEGER,
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_serviceProducts_org ON "serviceProducts" ("orgId");
CREATE INDEX IF NOT EXISTS idx_serviceProducts_loc ON "serviceProducts" ("locationId");

CREATE TABLE IF NOT EXISTS coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  code VARCHAR(255),
  "codePrefix" VARCHAR(255),
  "codeSuffix" VARCHAR(255),
  "codeStartNumber" INTEGER,
  "codeLength" INTEGER,
  "couponQuantity" INTEGER,
  "autoGenerateCodes" VARCHAR(255),
  "eligibleLocationIds" TEXT,
  "allowWithOtherDiscounts" VARCHAR(255),
  "allowWithLoyalty" VARCHAR(255),
  title VARCHAR(255),
  description TEXT,
  "discountType" VARCHAR(255),
  "discountValue" NUMERIC,
  "maxDiscount" NUMERIC,
  "flatPrice" NUMERIC,
  "buyQty" INTEGER,
  "freeQty" INTEGER,
  "freeItemName" VARCHAR(255),
  "appliesTo" VARCHAR(255),
  "targetIds" TEXT,
  "targetNames" TEXT,
  "minBillAmount" NUMERIC,
  "minQuantity" INTEGER,
  "minBookingValue" INTEGER,
  "customerSegment" VARCHAR(255),
  "targetCustomerId" BIGINT,
  "discountSlabs" TEXT,
  "inactiveDays" INTEGER,
  "staffId" BIGINT,
  "paymentMethod" VARCHAR(255),
  "firstAppointmentOnly" VARCHAR(255),
  "advanceBookingDays" INTEGER,
  "validityStart" DATE,
  "validityEnd" DATE,
  "validDays" VARCHAR(255),
  "validTimeStart" TIME,
  "validTimeEnd" TIME,
  "flashEndsAt" VARCHAR(255),
  "usageLimitMode" VARCHAR(255),
  "totalUsageLimit" NUMERIC,
  "perCustomerLimit" INTEGER,
  "usageCount" INTEGER,
  status VARCHAR(255),
  "campaignTag" VARCHAR(255),
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_coupons_org ON coupons ("orgId");
CREATE INDEX IF NOT EXISTS idx_coupons_loc ON coupons ("locationId");

CREATE TABLE IF NOT EXISTS vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  "couponId" BIGINT,
  code VARCHAR(255),
  "voucherType" VARCHAR(255),
  amount NUMERIC,
  "issueTo" VARCHAR(255),
  "customerId" BIGINT,
  "billId" BIGINT,
  "invoiceId" BIGINT,
  status VARCHAR(255),
  unlimited VARCHAR(255),
  "issuedAt" VARCHAR(255),
  "redeemedAt" VARCHAR(255),
  "schemeCode" VARCHAR(255),
  "schemeTitle" VARCHAR(255),
  "poolIndex" INTEGER,
  "poolGenerated" VARCHAR(255),
  "discountAmount" NUMERIC,
  "redeemedLocationId" BIGINT,
  createdby VARCHAR(255),
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_vouchers_org ON vouchers ("orgId");
CREATE INDEX IF NOT EXISTS idx_vouchers_loc ON vouchers ("locationId");

CREATE TABLE IF NOT EXISTS vendors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orgId" BIGINT NOT NULL,
  "locationId" BIGINT,
  name VARCHAR(255),
  contact VARCHAR(255),
  phone VARCHAR(255),
  email VARCHAR(255),
  gstin VARCHAR(255),
  outlet VARCHAR(255),
  category VARCHAR(255),
  status VARCHAR(255),
  notes TEXT,
  createdon DATE,
  updatedby VARCHAR(255),
  updatedon DATE
);

CREATE INDEX IF NOT EXISTS idx_vendors_org ON vendors ("orgId");
CREATE INDEX IF NOT EXISTS idx_vendors_loc ON vendors ("locationId");

COMMIT;
