/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugRouteImport } from './routes/$orgSlug'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as BookRouteImport } from './routes/book'
import { Route as BrandAppsRouteImport } from './routes/brand-apps'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FranchisesRouteImport } from './routes/franchises'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LeavesRouteImport } from './routes/leaves'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as MembershipsRouteImport } from './routes/memberships'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PosRouteImport } from './routes/pos'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandAppsRoute = BrandAppsRouteImport.update({
  id: '/brand-apps',
  path: '/brand-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchisesRoute = FranchisesRouteImport.update({
  id: '/franchises',
  path: '/franchises',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesRoute = LeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsRoute = MembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRoute
  '/appointments': typeof AppointmentsRoute
  '/attendance': typeof AttendanceRoute
  '/book': typeof BookRoute
  '/brand-apps': typeof BrandAppsRoute
  '/campaigns': typeof CampaignsRoute
  '/commissions': typeof CommissionsRoute
  '/crm': typeof CrmRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/feedback': typeof FeedbackRoute
  '/franchises': typeof FranchisesRoute
  '/inventory': typeof InventoryRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/memberships': typeof MembershipsRoute
  '/nearby': typeof NearbyRoute
  '/payroll': typeof PayrollRoute
  '/platform': typeof PlatformRoute
  '/pos': typeof PosRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/subscription': typeof SubscriptionRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRoute
  '/appointments': typeof AppointmentsRoute
  '/attendance': typeof AttendanceRoute
  '/book': typeof BookRoute
  '/brand-apps': typeof BrandAppsRoute
  '/campaigns': typeof CampaignsRoute
  '/commissions': typeof CommissionsRoute
  '/crm': typeof CrmRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/feedback': typeof FeedbackRoute
  '/franchises': typeof FranchisesRoute
  '/inventory': typeof InventoryRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/memberships': typeof MembershipsRoute
  '/nearby': typeof NearbyRoute
  '/payroll': typeof PayrollRoute
  '/platform': typeof PlatformRoute
  '/pos': typeof PosRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/subscription': typeof SubscriptionRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRoute
  '/appointments': typeof AppointmentsRoute
  '/attendance': typeof AttendanceRoute
  '/book': typeof BookRoute
  '/brand-apps': typeof BrandAppsRoute
  '/campaigns': typeof CampaignsRoute
  '/commissions': typeof CommissionsRoute
  '/crm': typeof CrmRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/feedback': typeof FeedbackRoute
  '/franchises': typeof FranchisesRoute
  '/inventory': typeof InventoryRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/memberships': typeof MembershipsRoute
  '/nearby': typeof NearbyRoute
  '/payroll': typeof PayrollRoute
  '/platform': typeof PlatformRoute
  '/pos': typeof PosRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/subscription': typeof SubscriptionRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/appointments'
    | '/attendance'
    | '/book'
    | '/brand-apps'
    | '/campaigns'
    | '/commissions'
    | '/crm'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/feedback'
    | '/franchises'
    | '/inventory'
    | '/leaves'
    | '/login'
    | '/loyalty'
    | '/memberships'
    | '/nearby'
    | '/payroll'
    | '/platform'
    | '/pos'
    | '/register'
    | '/roles'
    | '/services'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/subscription'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$orgSlug'
    | '/appointments'
    | '/attendance'
    | '/book'
    | '/brand-apps'
    | '/campaigns'
    | '/commissions'
    | '/crm'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/feedback'
    | '/franchises'
    | '/inventory'
    | '/leaves'
    | '/login'
    | '/loyalty'
    | '/memberships'
    | '/nearby'
    | '/payroll'
    | '/platform'
    | '/pos'
    | '/register'
    | '/roles'
    | '/services'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/subscription'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/appointments'
    | '/attendance'
    | '/book'
    | '/brand-apps'
    | '/campaigns'
    | '/commissions'
    | '/crm'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/feedback'
    | '/franchises'
    | '/inventory'
    | '/leaves'
    | '/login'
    | '/loyalty'
    | '/memberships'
    | '/nearby'
    | '/payroll'
    | '/platform'
    | '/pos'
    | '/register'
    | '/roles'
    | '/services'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/subscription'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRoute: typeof OrgSlugRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AttendanceRoute: typeof AttendanceRoute
  BookRoute: typeof BookRoute
  BrandAppsRoute: typeof BrandAppsRoute
  CampaignsRoute: typeof CampaignsRoute
  CommissionsRoute: typeof CommissionsRoute
  CrmRoute: typeof CrmRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  ExpensesRoute: typeof ExpensesRoute
  FeedbackRoute: typeof FeedbackRoute
  FranchisesRoute: typeof FranchisesRoute
  InventoryRoute: typeof InventoryRoute
  LeavesRoute: typeof LeavesRoute
  LoginRoute: typeof LoginRoute
  LoyaltyRoute: typeof LoyaltyRoute
  MembershipsRoute: typeof MembershipsRoute
  NearbyRoute: typeof NearbyRoute
  PayrollRoute: typeof PayrollRoute
  PlatformRoute: typeof PlatformRoute
  PosRoute: typeof PosRoute
  RegisterRoute: typeof RegisterRoute
  RolesRoute: typeof RolesRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  ShiftsRoute: typeof ShiftsRoute
  StaffRoute: typeof StaffRoute
  SubscriptionRoute: typeof SubscriptionRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-apps': {
      id: '/brand-apps'
      path: '/brand-apps'
      fullPath: '/brand-apps'
      preLoaderRoute: typeof BrandAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchises': {
      id: '/franchises'
      path: '/franchises'
      fullPath: '/franchises'
      preLoaderRoute: typeof FranchisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves': {
      id: '/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof LeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships': {
      id: '/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof MembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRoute: OrgSlugRoute,
  AppointmentsRoute: AppointmentsRoute,
  AttendanceRoute: AttendanceRoute,
  BookRoute: BookRoute,
  BrandAppsRoute: BrandAppsRoute,
  CampaignsRoute: CampaignsRoute,
  CommissionsRoute: CommissionsRoute,
  CrmRoute: CrmRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  ExpensesRoute: ExpensesRoute,
  FeedbackRoute: FeedbackRoute,
  FranchisesRoute: FranchisesRoute,
  InventoryRoute: InventoryRoute,
  LeavesRoute: LeavesRoute,
  LoginRoute: LoginRoute,
  LoyaltyRoute: LoyaltyRoute,
  MembershipsRoute: MembershipsRoute,
  NearbyRoute: NearbyRoute,
  PayrollRoute: PayrollRoute,
  PlatformRoute: PlatformRoute,
  PosRoute: PosRoute,
  RegisterRoute: RegisterRoute,
  RolesRoute: RolesRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  ShiftsRoute: ShiftsRoute,
  StaffRoute: StaffRoute,
  SubscriptionRoute: SubscriptionRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
