/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugRouteImport } from './routes/$orgSlug'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as BookRouteImport } from './routes/book'
import { Route as BrandAppsRouteImport } from './routes/brand-apps'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FranchisesRouteImport } from './routes/franchises'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LeavesRouteImport } from './routes/leaves'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as MembershipsRouteImport } from './routes/memberships'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PosRouteImport } from './routes/pos'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as UsersRouteImport } from './routes/users'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as LoyaltyIndexRouteImport } from './routes/loyalty/index'
import { Route as LoyaltyCatalogRouteImport } from './routes/loyalty/catalog'
import { Route as LoyaltyCheckinsRouteImport } from './routes/loyalty/checkins'
import { Route as LoyaltyHistoryRouteImport } from './routes/loyalty/history'
import { Route as LoyaltyLedgerRouteImport } from './routes/loyalty/ledger'
import { Route as LoyaltyOffersRouteImport } from './routes/loyalty/offers'
import { Route as LoyaltyOverviewRouteImport } from './routes/loyalty/overview'
import { Route as LoyaltyPartnersRouteImport } from './routes/loyalty/partners'
import { Route as LoyaltyProgramsRouteImport } from './routes/loyalty/programs'
import { Route as LoyaltyQrRouteImport } from './routes/loyalty/qr'
import { Route as LoyaltyRedemptionsRouteImport } from './routes/loyalty/redemptions'
import { Route as LoyaltyRewardsRouteImport } from './routes/loyalty/rewards'
import { Route as LoyaltyWheelRouteImport } from './routes/loyalty/wheel'
import { Route as QrLocationIdRouteImport } from './routes/qr.$locationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandAppsRoute = BrandAppsRouteImport.update({
  id: '/brand-apps',
  path: '/brand-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchisesRoute = FranchisesRouteImport.update({
  id: '/franchises',
  path: '/franchises',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesRoute = LeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsRoute = MembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)
const LoyaltyIndexRoute = LoyaltyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoyaltyRoute,
} as any)
const LoyaltyCatalogRoute = LoyaltyCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => LoyaltyRoute,
} as any)
const LoyaltyCheckinsRoute = LoyaltyCheckinsRouteImport.update({
  id: '/checkins',
  path: '/checkins',
  getParentRoute: () => LoyaltyRoute,
} as any)
const LoyaltyHistoryRoute = LoyaltyHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LoyaltyRoute,
} as any)
const LoyaltyLedgerRoute = LoyaltyLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => LoyaltyRoute,
} as any)
const LoyaltyOffersRoute = LoyaltyOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => LoyaltyRoute,
} as any)
const LoyaltyOverviewRoute = LoyaltyOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => LoyaltyRoute,
} as any)
const LoyaltyPartnersRoute = LoyaltyPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => LoyaltyRoute,
} as any)
const LoyaltyProgramsRoute = LoyaltyProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => LoyaltyRoute,
} as any)
const LoyaltyQrRoute = LoyaltyQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => LoyaltyRoute,
} as any)
const LoyaltyRedemptionsRoute = LoyaltyRedemptionsRouteImport.update({
  id: '/redemptions',
  path: '/redemptions',
  getParentRoute: () => LoyaltyRoute,
} as any)
const LoyaltyRewardsRoute = LoyaltyRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => LoyaltyRoute,
} as any)
const LoyaltyWheelRoute = LoyaltyWheelRouteImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => LoyaltyRoute,
} as any)
const QrLocationIdRoute = QrLocationIdRouteImport.update({
  id: '/qr/$locationId',
  path: '/qr/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRoute
  '/appointments': typeof AppointmentsRoute
  '/attendance': typeof AttendanceRoute
  '/book': typeof BookRoute
  '/brand-apps': typeof BrandAppsRoute
  '/campaigns': typeof CampaignsRoute
  '/commissions': typeof CommissionsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/feedback': typeof FeedbackRoute
  '/franchises': typeof FranchisesRoute
  '/inventory': typeof InventoryRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRouteWithChildren
  '/memberships': typeof MembershipsRoute
  '/nearby': typeof NearbyRoute
  '/offers': typeof OffersRoute
  '/payroll': typeof PayrollRoute
  '/platform': typeof PlatformRoute
  '/pos': typeof PosRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/subscription': typeof SubscriptionRoute
  '/users': typeof UsersRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/loyalty/catalog': typeof LoyaltyCatalogRoute
  '/loyalty/checkins': typeof LoyaltyCheckinsRoute
  '/loyalty/history': typeof LoyaltyHistoryRoute
  '/loyalty/ledger': typeof LoyaltyLedgerRoute
  '/loyalty/offers': typeof LoyaltyOffersRoute
  '/loyalty/overview': typeof LoyaltyOverviewRoute
  '/loyalty/partners': typeof LoyaltyPartnersRoute
  '/loyalty/programs': typeof LoyaltyProgramsRoute
  '/loyalty/qr': typeof LoyaltyQrRoute
  '/loyalty/redemptions': typeof LoyaltyRedemptionsRoute
  '/loyalty/rewards': typeof LoyaltyRewardsRoute
  '/loyalty/wheel': typeof LoyaltyWheelRoute
  '/qr/$locationId': typeof QrLocationIdRoute
  '/loyalty/': typeof LoyaltyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRoute
  '/appointments': typeof AppointmentsRoute
  '/attendance': typeof AttendanceRoute
  '/book': typeof BookRoute
  '/brand-apps': typeof BrandAppsRoute
  '/campaigns': typeof CampaignsRoute
  '/commissions': typeof CommissionsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/feedback': typeof FeedbackRoute
  '/franchises': typeof FranchisesRoute
  '/inventory': typeof InventoryRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/memberships': typeof MembershipsRoute
  '/nearby': typeof NearbyRoute
  '/offers': typeof OffersRoute
  '/payroll': typeof PayrollRoute
  '/platform': typeof PlatformRoute
  '/pos': typeof PosRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/subscription': typeof SubscriptionRoute
  '/users': typeof UsersRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/loyalty/catalog': typeof LoyaltyCatalogRoute
  '/loyalty/checkins': typeof LoyaltyCheckinsRoute
  '/loyalty/history': typeof LoyaltyHistoryRoute
  '/loyalty/ledger': typeof LoyaltyLedgerRoute
  '/loyalty/offers': typeof LoyaltyOffersRoute
  '/loyalty/overview': typeof LoyaltyOverviewRoute
  '/loyalty/partners': typeof LoyaltyPartnersRoute
  '/loyalty/programs': typeof LoyaltyProgramsRoute
  '/loyalty/qr': typeof LoyaltyQrRoute
  '/loyalty/redemptions': typeof LoyaltyRedemptionsRoute
  '/loyalty/rewards': typeof LoyaltyRewardsRoute
  '/loyalty/wheel': typeof LoyaltyWheelRoute
  '/qr/$locationId': typeof QrLocationIdRoute
  '/loyalty': typeof LoyaltyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRoute
  '/appointments': typeof AppointmentsRoute
  '/attendance': typeof AttendanceRoute
  '/book': typeof BookRoute
  '/brand-apps': typeof BrandAppsRoute
  '/campaigns': typeof CampaignsRoute
  '/commissions': typeof CommissionsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/feedback': typeof FeedbackRoute
  '/franchises': typeof FranchisesRoute
  '/inventory': typeof InventoryRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRouteWithChildren
  '/memberships': typeof MembershipsRoute
  '/nearby': typeof NearbyRoute
  '/offers': typeof OffersRoute
  '/payroll': typeof PayrollRoute
  '/platform': typeof PlatformRoute
  '/pos': typeof PosRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/subscription': typeof SubscriptionRoute
  '/users': typeof UsersRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/loyalty/catalog': typeof LoyaltyCatalogRoute
  '/loyalty/checkins': typeof LoyaltyCheckinsRoute
  '/loyalty/history': typeof LoyaltyHistoryRoute
  '/loyalty/ledger': typeof LoyaltyLedgerRoute
  '/loyalty/offers': typeof LoyaltyOffersRoute
  '/loyalty/overview': typeof LoyaltyOverviewRoute
  '/loyalty/partners': typeof LoyaltyPartnersRoute
  '/loyalty/programs': typeof LoyaltyProgramsRoute
  '/loyalty/qr': typeof LoyaltyQrRoute
  '/loyalty/redemptions': typeof LoyaltyRedemptionsRoute
  '/loyalty/rewards': typeof LoyaltyRewardsRoute
  '/loyalty/wheel': typeof LoyaltyWheelRoute
  '/qr/$locationId': typeof QrLocationIdRoute
  '/loyalty/': typeof LoyaltyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/appointments'
    | '/attendance'
    | '/book'
    | '/brand-apps'
    | '/campaigns'
    | '/commissions'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/feedback'
    | '/franchises'
    | '/inventory'
    | '/leaves'
    | '/login'
    | '/loyalty'
    | '/memberships'
    | '/nearby'
    | '/offers'
    | '/payroll'
    | '/platform'
    | '/pos'
    | '/register'
    | '/roles'
    | '/services'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/subscription'
    | '/users'
    | '/customers/$customerId'
    | '/loyalty/catalog'
    | '/loyalty/checkins'
    | '/loyalty/history'
    | '/loyalty/ledger'
    | '/loyalty/offers'
    | '/loyalty/overview'
    | '/loyalty/partners'
    | '/loyalty/programs'
    | '/loyalty/qr'
    | '/loyalty/redemptions'
    | '/loyalty/rewards'
    | '/loyalty/wheel'
    | '/qr/$locationId'
    | '/loyalty/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$orgSlug'
    | '/appointments'
    | '/attendance'
    | '/book'
    | '/brand-apps'
    | '/campaigns'
    | '/commissions'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/feedback'
    | '/franchises'
    | '/inventory'
    | '/leaves'
    | '/login'
    | '/memberships'
    | '/nearby'
    | '/offers'
    | '/payroll'
    | '/platform'
    | '/pos'
    | '/register'
    | '/roles'
    | '/services'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/subscription'
    | '/users'
    | '/customers/$customerId'
    | '/loyalty/catalog'
    | '/loyalty/checkins'
    | '/loyalty/history'
    | '/loyalty/ledger'
    | '/loyalty/offers'
    | '/loyalty/overview'
    | '/loyalty/partners'
    | '/loyalty/programs'
    | '/loyalty/qr'
    | '/loyalty/redemptions'
    | '/loyalty/rewards'
    | '/loyalty/wheel'
    | '/qr/$locationId'
    | '/loyalty'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/appointments'
    | '/attendance'
    | '/book'
    | '/brand-apps'
    | '/campaigns'
    | '/commissions'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/feedback'
    | '/franchises'
    | '/inventory'
    | '/leaves'
    | '/login'
    | '/loyalty'
    | '/memberships'
    | '/nearby'
    | '/offers'
    | '/payroll'
    | '/platform'
    | '/pos'
    | '/register'
    | '/roles'
    | '/services'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/subscription'
    | '/users'
    | '/customers/$customerId'
    | '/loyalty/catalog'
    | '/loyalty/checkins'
    | '/loyalty/history'
    | '/loyalty/ledger'
    | '/loyalty/offers'
    | '/loyalty/overview'
    | '/loyalty/partners'
    | '/loyalty/programs'
    | '/loyalty/qr'
    | '/loyalty/redemptions'
    | '/loyalty/rewards'
    | '/loyalty/wheel'
    | '/qr/$locationId'
    | '/loyalty/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRoute: typeof OrgSlugRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AttendanceRoute: typeof AttendanceRoute
  BookRoute: typeof BookRoute
  BrandAppsRoute: typeof BrandAppsRoute
  CampaignsRoute: typeof CampaignsRoute
  CommissionsRoute: typeof CommissionsRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ExpensesRoute: typeof ExpensesRoute
  FeedbackRoute: typeof FeedbackRoute
  FranchisesRoute: typeof FranchisesRoute
  InventoryRoute: typeof InventoryRoute
  LeavesRoute: typeof LeavesRoute
  LoginRoute: typeof LoginRoute
  LoyaltyRoute: typeof LoyaltyRouteWithChildren
  MembershipsRoute: typeof MembershipsRoute
  NearbyRoute: typeof NearbyRoute
  OffersRoute: typeof OffersRoute
  PayrollRoute: typeof PayrollRoute
  PlatformRoute: typeof PlatformRoute
  PosRoute: typeof PosRoute
  RegisterRoute: typeof RegisterRoute
  RolesRoute: typeof RolesRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  ShiftsRoute: typeof ShiftsRoute
  StaffRoute: typeof StaffRoute
  SubscriptionRoute: typeof SubscriptionRoute
  UsersRoute: typeof UsersRoute
  QrLocationIdRoute: typeof QrLocationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-apps': {
      id: '/brand-apps'
      path: '/brand-apps'
      fullPath: '/brand-apps'
      preLoaderRoute: typeof BrandAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchises': {
      id: '/franchises'
      path: '/franchises'
      fullPath: '/franchises'
      preLoaderRoute: typeof FranchisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves': {
      id: '/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof LeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships': {
      id: '/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof MembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/loyalty/': {
      id: '/loyalty/'
      path: '/'
      fullPath: '/loyalty/'
      preLoaderRoute: typeof LoyaltyIndexRouteImport
      parentRoute: typeof LoyaltyRoute
    }
    '/loyalty/catalog': {
      id: '/loyalty/catalog'
      path: '/catalog'
      fullPath: '/loyalty/catalog'
      preLoaderRoute: typeof LoyaltyCatalogRouteImport
      parentRoute: typeof LoyaltyRoute
    }
    '/loyalty/checkins': {
      id: '/loyalty/checkins'
      path: '/checkins'
      fullPath: '/loyalty/checkins'
      preLoaderRoute: typeof LoyaltyCheckinsRouteImport
      parentRoute: typeof LoyaltyRoute
    }
    '/loyalty/history': {
      id: '/loyalty/history'
      path: '/history'
      fullPath: '/loyalty/history'
      preLoaderRoute: typeof LoyaltyHistoryRouteImport
      parentRoute: typeof LoyaltyRoute
    }
    '/loyalty/ledger': {
      id: '/loyalty/ledger'
      path: '/ledger'
      fullPath: '/loyalty/ledger'
      preLoaderRoute: typeof LoyaltyLedgerRouteImport
      parentRoute: typeof LoyaltyRoute
    }
    '/loyalty/offers': {
      id: '/loyalty/offers'
      path: '/offers'
      fullPath: '/loyalty/offers'
      preLoaderRoute: typeof LoyaltyOffersRouteImport
      parentRoute: typeof LoyaltyRoute
    }
    '/loyalty/overview': {
      id: '/loyalty/overview'
      path: '/overview'
      fullPath: '/loyalty/overview'
      preLoaderRoute: typeof LoyaltyOverviewRouteImport
      parentRoute: typeof LoyaltyRoute
    }
    '/loyalty/partners': {
      id: '/loyalty/partners'
      path: '/partners'
      fullPath: '/loyalty/partners'
      preLoaderRoute: typeof LoyaltyPartnersRouteImport
      parentRoute: typeof LoyaltyRoute
    }
    '/loyalty/programs': {
      id: '/loyalty/programs'
      path: '/programs'
      fullPath: '/loyalty/programs'
      preLoaderRoute: typeof LoyaltyProgramsRouteImport
      parentRoute: typeof LoyaltyRoute
    }
    '/loyalty/qr': {
      id: '/loyalty/qr'
      path: '/qr'
      fullPath: '/loyalty/qr'
      preLoaderRoute: typeof LoyaltyQrRouteImport
      parentRoute: typeof LoyaltyRoute
    }
    '/loyalty/redemptions': {
      id: '/loyalty/redemptions'
      path: '/redemptions'
      fullPath: '/loyalty/redemptions'
      preLoaderRoute: typeof LoyaltyRedemptionsRouteImport
      parentRoute: typeof LoyaltyRoute
    }
    '/loyalty/rewards': {
      id: '/loyalty/rewards'
      path: '/rewards'
      fullPath: '/loyalty/rewards'
      preLoaderRoute: typeof LoyaltyRewardsRouteImport
      parentRoute: typeof LoyaltyRoute
    }
    '/loyalty/wheel': {
      id: '/loyalty/wheel'
      path: '/wheel'
      fullPath: '/loyalty/wheel'
      preLoaderRoute: typeof LoyaltyWheelRouteImport
      parentRoute: typeof LoyaltyRoute
    }
    '/qr/$locationId': {
      id: '/qr/$locationId'
      path: '/qr/$locationId'
      fullPath: '/qr/$locationId'
      preLoaderRoute: typeof QrLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface LoyaltyRouteChildren {
  LoyaltyCatalogRoute: typeof LoyaltyCatalogRoute
  LoyaltyCheckinsRoute: typeof LoyaltyCheckinsRoute
  LoyaltyHistoryRoute: typeof LoyaltyHistoryRoute
  LoyaltyLedgerRoute: typeof LoyaltyLedgerRoute
  LoyaltyOffersRoute: typeof LoyaltyOffersRoute
  LoyaltyOverviewRoute: typeof LoyaltyOverviewRoute
  LoyaltyPartnersRoute: typeof LoyaltyPartnersRoute
  LoyaltyProgramsRoute: typeof LoyaltyProgramsRoute
  LoyaltyQrRoute: typeof LoyaltyQrRoute
  LoyaltyRedemptionsRoute: typeof LoyaltyRedemptionsRoute
  LoyaltyRewardsRoute: typeof LoyaltyRewardsRoute
  LoyaltyWheelRoute: typeof LoyaltyWheelRoute
  LoyaltyIndexRoute: typeof LoyaltyIndexRoute
}

const LoyaltyRouteChildren: LoyaltyRouteChildren = {
  LoyaltyCatalogRoute: LoyaltyCatalogRoute,
  LoyaltyCheckinsRoute: LoyaltyCheckinsRoute,
  LoyaltyHistoryRoute: LoyaltyHistoryRoute,
  LoyaltyLedgerRoute: LoyaltyLedgerRoute,
  LoyaltyOffersRoute: LoyaltyOffersRoute,
  LoyaltyOverviewRoute: LoyaltyOverviewRoute,
  LoyaltyPartnersRoute: LoyaltyPartnersRoute,
  LoyaltyProgramsRoute: LoyaltyProgramsRoute,
  LoyaltyQrRoute: LoyaltyQrRoute,
  LoyaltyRedemptionsRoute: LoyaltyRedemptionsRoute,
  LoyaltyRewardsRoute: LoyaltyRewardsRoute,
  LoyaltyWheelRoute: LoyaltyWheelRoute,
  LoyaltyIndexRoute: LoyaltyIndexRoute,
}

const LoyaltyRouteWithChildren =
  LoyaltyRoute._addFileChildren(LoyaltyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRoute: OrgSlugRoute,
  AppointmentsRoute: AppointmentsRoute,
  AttendanceRoute: AttendanceRoute,
  BookRoute: BookRoute,
  BrandAppsRoute: BrandAppsRoute,
  CampaignsRoute: CampaignsRoute,
  CommissionsRoute: CommissionsRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ExpensesRoute: ExpensesRoute,
  FeedbackRoute: FeedbackRoute,
  FranchisesRoute: FranchisesRoute,
  InventoryRoute: InventoryRoute,
  LeavesRoute: LeavesRoute,
  LoginRoute: LoginRoute,
  LoyaltyRoute: LoyaltyRouteWithChildren,
  MembershipsRoute: MembershipsRoute,
  NearbyRoute: NearbyRoute,
  OffersRoute: OffersRoute,
  PayrollRoute: PayrollRoute,
  PlatformRoute: PlatformRoute,
  PosRoute: PosRoute,
  RegisterRoute: RegisterRoute,
  RolesRoute: RolesRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  ShiftsRoute: ShiftsRoute,
  StaffRoute: StaffRoute,
  SubscriptionRoute: SubscriptionRoute,
  UsersRoute: UsersRoute,
  QrLocationIdRoute: QrLocationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
