import seed from "@/data/salonData.json";

export type FieldType = "text" | "number" | "date" | "time" | "textarea" | "select";

export type Field = {
  name: string;
  label: string;
  type?: FieldType;
  options?: string[];
  table?: boolean;
  /** When false, the field is table/search only and not shown in the edit form. Default true. */
  form?: boolean;
  badge?: boolean;
  money?: boolean;
};

export type ModuleDef = {
  key: string;
  title: string;
  subtitle: string;
  idPrefix: string;
  fields: Field[];
};

const unique = (values: string[]) => [...new Set(values.filter(Boolean))];
const outlets = ["All", ...unique(seed.locations.map((l) => l.name))];
const staffNames = unique(seed.staff.map((s) => s.name));
const customerNames = unique(seed.customers.map((c) => c.name));
const membershipPlanNames = unique(seed.membershipPlans.map((p) => p.name));
const workspaceRoleNames = unique(
  ((seed as { roles?: { name: string }[] }).roles ?? []).map((r) => r.name).concat([
    "Owner",
    "Franchise Manager",
    "Outlet Manager",
    "Stylist",
    "Receptionist",
  ]),
);

export const modules = {
  customers: {
    key: "customers",
    title: "Customers",
    subtitle: "Customer master, households, tiers, wallet and loyalty balances.",
    idPrefix: "C-",
    fields: [
      { name: "name", label: "Full name", table: true },
      { name: "phone", label: "Phone", table: true },
      { name: "email", label: "Email" },
      { name: "gender", label: "Gender", type: "select", options: ["Female", "Male", "Other"] },
      { name: "birthday", label: "Birthday", type: "date" },
      { name: "anniversary", label: "Anniversary", type: "date" },
      { name: "household", label: "Household / family" },
      { name: "tier", label: "Tier", type: "select", options: ["Silver", "Gold", "Platinum"], table: true, badge: true },
      { name: "points", label: "Loyalty points", type: "number", table: true, form: false },
      { name: "walletBalance", label: "Wallet balance", type: "number", money: true, table: true },
      { name: "membershipId", label: "Membership", table: true, form: false },
      { name: "outlet", label: "Home outlet", type: "select", options: outlets, table: true },
      { name: "lastVisit", label: "Last visit", type: "date", table: true },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  appointments: {
    key: "appointments",
    title: "Appointments",
    subtitle: "Bookings across outlets, stylists and channels.",
    idPrefix: "A-",
    fields: [
      { name: "customer", label: "Customer", type: "select", options: customerNames, table: true },
      { name: "service", label: "Service", table: true },
      { name: "staff", label: "Stylist", type: "select", options: staffNames, table: true },
      { name: "outlet", label: "Outlet", type: "select", options: outlets, table: true },
      { name: "date", label: "Date", type: "date", table: true },
      { name: "time", label: "Time", type: "time", table: true },
      { name: "duration", label: "Duration (min)", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Pending", "Confirmed", "Completed", "Cancelled", "No-show"],
        table: true,
        badge: true,
      },
      {
        name: "source",
        label: "Source",
        type: "select",
        options: ["Walk-in", "Phone", "WhatsApp", "Instagram", "Customer App"],
      },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  invoices: {
    key: "invoices",
    title: "POS & Billing",
    subtitle: "GST-compliant invoices, discounts, payments and refunds.",
    idPrefix: "INV-",
    fields: [
      { name: "customer", label: "Customer", type: "select", options: customerNames, table: true },
      { name: "outlet", label: "Outlet", type: "select", options: outlets, table: true },
      { name: "date", label: "Invoice date", type: "date", table: true },
      { name: "items", label: "Line items", type: "textarea", table: true },
      { name: "subtotal", label: "Subtotal", type: "number", money: true },
      { name: "discount", label: "Discount", type: "number", money: true },
      { name: "gstRate", label: "GST %", type: "select", options: ["0", "5", "12", "18", "28"] },
      { name: "tax", label: "Tax amount", type: "number", money: true },
      { name: "total", label: "Total", type: "number", money: true, table: true },
      {
        name: "payment",
        label: "Payment mode",
        type: "select",
        options: ["Cash", "Card", "UPI", "Wallet + Card", "Split"],
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Paid", "Unpaid", "Refunded"],
        table: true,
        badge: true,
      },
    ],
  },
  services: {
    key: "services",
    title: "Service Catalogue",
    subtitle: "Single services and combos with pricing, GST slabs and commission rates.",
    idPrefix: "S-",
    fields: [
      {
        name: "type",
        label: "Type",
        type: "select",
        options: ["Single", "Combo"],
        table: true,
        badge: true,
      },
      { name: "name", label: "Service name", table: true },
      {
        name: "category",
        label: "Category",
        type: "select",
        options: ["Hair", "Skin", "Grooming", "Bridal", "Spa"],
        table: true,
      },
      { name: "duration", label: "Duration (min)", type: "number", table: true },
      { name: "price", label: "Price", type: "number", money: true, table: true },
      { name: "gstRate", label: "GST %", type: "select", options: ["0", "5", "12", "18", "28"] },
      { name: "commission", label: "Commission %", type: "number", table: true },
      { name: "outlet", label: "Available at", type: "select", options: outlets },
      { name: "active", label: "Active", type: "select", options: ["Yes", "No"], table: true, badge: true },
    ],
  },
  inventory: {
    key: "inventory",
    title: "Inventory",
    subtitle: "Retail, back-bar and consumable stock with reorder levels.",
    idPrefix: "SKU-",
    fields: [
      { name: "name", label: "Item name", table: true },
      {
        name: "category",
        label: "Category",
        type: "select",
        options: ["Retail", "Back-bar", "Consumable"],
        table: true,
        badge: true,
      },
      { name: "brand", label: "Brand" },
      { name: "outlet", label: "Outlet", type: "select", options: outlets, table: true },
      { name: "stock", label: "Remaining", type: "number", table: true, form: false },
      { name: "reorderLevel", label: "Reorder level", type: "number", table: true },
      { name: "unitCost", label: "Unit cost", type: "number", money: true },
      { name: "sellPrice", label: "Retail price", type: "number", money: true, table: true },
      { name: "batch", label: "Batch / lot" },
      { name: "expiry", label: "Expiry", type: "date" },
    ],
  },
  expenses: {
    key: "expenses",
    title: "Expenses",
    subtitle: "Outlet spend with approval workflow.",
    idPrefix: "EXP-",
    fields: [
      {
        name: "category",
        label: "Category",
        type: "select",
        options: ["Rent", "Utilities", "Purchase", "Marketing", "Maintenance", "Salary", "Other"],
        table: true,
      },
      { name: "vendor", label: "Vendor", table: true },
      { name: "outlet", label: "Outlet", type: "select", options: outlets, table: true },
      { name: "date", label: "Date", type: "date", table: true },
      { name: "amount", label: "Amount", type: "number", money: true, table: true },
      { name: "payment", label: "Payment mode", type: "select", options: ["Cash", "Card", "UPI", "Bank Transfer"] },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Pending", "Approved", "Rejected"],
        table: true,
        badge: true,
      },
      { name: "approver", label: "Approved by" },
      { name: "notes", label: "Notes", type: "textarea" },
      { name: "skuId", label: "Product SKU", table: true, form: false },
      { name: "quantity", label: "Qty received", type: "number", table: true, form: false },
      { name: "stockPosted", label: "Posted to stock", form: false },
    ],
  },
  staff: {
    key: "staff",
    title: "Staff",
    subtitle: "Staff master with salary, commission and targets.",
    idPrefix: "ST-",
    fields: [
      { name: "name", label: "Name", table: true },
      {
        name: "role",
        label: "Role",
        type: "select",
        options: ["Senior Stylist", "Hair Specialist", "Barber", "Beautician", "Outlet Manager", "Receptionist"],
        table: true,
      },
      { name: "outlet", label: "Outlet", type: "select", options: outlets, table: true },
      { name: "phone", label: "Phone", table: true },
      { name: "email", label: "Email" },
      { name: "joinDate", label: "Joining date", type: "date" },
      { name: "baseSalary", label: "Base salary", type: "number", money: true, table: true },
      { name: "commissionRate", label: "Commission %", type: "number" },
      { name: "target", label: "Monthly target", type: "number", money: true, table: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Active", "On Leave", "Inactive"],
        table: true,
        badge: true,
      },
    ],
  },
  shifts: {
    key: "shifts",
    title: "Shifts & Roster",
    subtitle: "Expected hours for attendance. Rosters are per staff ID, location and date.",
    idPrefix: "SH-",
    fields: [
      { name: "staffId", label: "Staff", type: "select", table: true },
      { name: "date", label: "Date", type: "date", table: true },
      { name: "startTime", label: "Start", type: "time", table: true },
      { name: "endTime", label: "End", type: "time", table: true },
      {
        name: "shiftType",
        label: "Shift type",
        type: "select",
        options: ["Morning", "Evening", "General", "Split"],
        table: true,
      },
      {
        name: "weeklyOff",
        label: "Weekly off",
        type: "select",
        options: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
      },
      { name: "status", label: "Status", type: "select", options: ["Draft", "Published"], table: true, badge: true },
    ],
  },
  attendance: {
    key: "attendance",
    title: "Attendance",
    subtitle: "Punches plus roster and approved leave. Status and hours are calculated, not typed.",
    idPrefix: "AT-",
    fields: [
      { name: "staffId", label: "Staff", type: "select", table: true },
      { name: "date", label: "Date", type: "date", table: true },
      { name: "checkIn", label: "Check in", type: "time", table: true },
      { name: "checkOut", label: "Check out", type: "time", table: true },
      { name: "hours", label: "Hours", type: "number", table: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Present", "Late", "Absent", "Leave", "Half Day"],
        table: true,
        badge: true,
      },
      { name: "outlet", label: "Outlet", type: "select", options: outlets, table: true },
      { name: "remarks", label: "Remarks", type: "textarea" },
    ],
  },
  leaves: {
    key: "leaves",
    title: "Leave Requests",
    subtitle: "Leave is the source for absence. Attendance reads approved dates; days are counted from From–To.",
    idPrefix: "LV-",
    fields: [
      { name: "staffId", label: "Staff", type: "select", table: true },
      {
        name: "type",
        label: "Leave type",
        type: "select",
        options: ["Casual Leave", "Sick Leave", "Paid Leave", "Unpaid Leave"],
        table: true,
      },
      { name: "fromDate", label: "From", type: "date", table: true },
      { name: "toDate", label: "To", type: "date", table: true },
      { name: "days", label: "Days", type: "number", table: true, form: false },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Pending", "Approved", "Rejected"],
        table: true,
        badge: true,
      },
      { name: "approver", label: "Approver" },
      { name: "reason", label: "Reason", type: "textarea" },
    ],
  },
  payroll: {
    key: "payroll",
    title: "Payroll",
    subtitle: "Monthly payroll runs with commission and deductions.",
    idPrefix: "PR-",
    fields: [
      { name: "staff", label: "Staff", type: "select", options: staffNames, table: true },
      { name: "period", label: "Period", table: true },
      { name: "baseSalary", label: "Base salary", type: "number", money: true, table: true },
      { name: "commission", label: "Commission", type: "number", money: true, table: true },
      { name: "incentive", label: "Incentive", type: "number", money: true },
      { name: "deductions", label: "Deductions", type: "number", money: true },
      { name: "netPay", label: "Net pay", type: "number", money: true, table: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Draft", "Approved", "Paid"],
        table: true,
        badge: true,
      },
      { name: "payDate", label: "Pay date", type: "date" },
    ],
  },
  commissions: {
    key: "commissions",
    title: "Commission Ledger",
    subtitle: "Per-transaction service and product commission entries.",
    idPrefix: "CM-",
    fields: [
      { name: "staff", label: "Staff", type: "select", options: staffNames, table: true },
      { name: "invoice", label: "Invoice", table: true },
      { name: "type", label: "Type", type: "select", options: ["Service", "Product"], table: true, badge: true },
      { name: "item", label: "Item", table: true },
      { name: "baseAmount", label: "Base amount", type: "number", money: true },
      { name: "rate", label: "Rate %", type: "number" },
      { name: "amount", label: "Commission", type: "number", money: true, table: true },
      { name: "date", label: "Date", type: "date", table: true },
      { name: "status", label: "Status", type: "select", options: ["Open", "Locked", "Paid"], table: true },
    ],
  },
  feedback: {
    key: "feedback",
    title: "Feedback",
    subtitle: "Ratings, NPS and service recovery pipeline.",
    idPrefix: "FB-",
    fields: [
      { name: "customer", label: "Customer", type: "select", options: customerNames, table: true },
      { name: "invoice", label: "Invoice" },
      { name: "staff", label: "Staff", type: "select", options: staffNames, table: true },
      { name: "outlet", label: "Outlet", type: "select", options: outlets, table: true },
      { name: "date", label: "Date", type: "date", table: true },
      { name: "rating", label: "Rating (1-5)", type: "number", table: true },
      { name: "nps", label: "NPS (0-10)", type: "number" },
      { name: "channel", label: "Channel", type: "select", options: ["WhatsApp", "SMS", "Email", "App"] },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["New", "Recovery Open", "Review Requested", "Closed"],
        table: true,
        badge: true,
      },
      { name: "comment", label: "Comment", type: "textarea", table: true },
    ],
  },
  loyalty: {
    key: "loyalty",
    title: "Loyalty Programs",
    subtitle: "Points, family offers and QR scan-to-earn campaigns.",
    idPrefix: "LY-",
    fields: [
      { name: "name", label: "Program name", table: true },
      {
        name: "type",
        label: "Type",
        type: "select",
        options: ["Points", "Stamp Card", "Spin the Wheel", "Tiered", "Family Offer", "Promotional QR", "Wallet"],
        table: true,
        badge: true,
      },
      { name: "earnRate", label: "Earn rate (display)", table: true },
      { name: "redeemValue", label: "Redemption value (display)", table: true },
      { name: "earnUnitRupees", label: "₹ per earn unit", type: "number" },
      { name: "pointsPerUnit", label: "Points per unit", type: "number" },
      { name: "rupeesPerPoint", label: "₹ per point (redeem)", type: "number" },
      { name: "tier", label: "Applies to tier", type: "select", options: ["All", "Silver", "Gold", "Platinum"] },
      { name: "minSpend", label: "Min spend", type: "number", money: true },
      { name: "expiryMonths", label: "Points expiry (months)", type: "number" },
      { name: "stampsRequired", label: "Stamps required", type: "number" },
      { name: "rewardDescription", label: "Stamp / wheel reward" },
      { name: "qrEnabled", label: "QR enabled", type: "select", options: ["Yes", "No"], table: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Active", "Scheduled", "Paused"],
        table: true,
        badge: true,
      },
    ],
  },
  membershipPlans: {
    key: "membershipPlans",
    title: "Membership plans",
    subtitle: "Reusable plan types. Many customers can enroll on the same plan.",
    idPrefix: "PLAN-",
    fields: [
      { name: "name", label: "Plan name", table: true },
      { name: "price", label: "Price", type: "number", money: true, table: true },
      { name: "validityMonths", label: "Validity (months)", type: "number", table: true },
      { name: "benefits", label: "Benefits", type: "textarea", table: true },
      { name: "includedMatch", label: "Included match (name/category keywords)", table: true },
      { name: "includedLimit", label: "Included visits (0 = unlimited)", type: "number", table: true },
      { name: "extraDiscountMatch", label: "Extra % match keywords" },
      { name: "extraDiscountPct", label: "Extra service discount %", type: "number" },
      { name: "retailDiscountPct", label: "Retail (product) discount %", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Active", "Paused"],
        table: true,
        badge: true,
      },
    ],
  },
  memberships: {
    key: "memberships",
    title: "Member enrollments",
    subtitle: "Assign a plan to a customer. The same plan can be sold to many members.",
    idPrefix: "MP-",
    fields: [
      { name: "planId", label: "Plan ID", table: true },
      { name: "plan", label: "Plan", type: "select", options: membershipPlanNames, table: true, badge: true },
      { name: "customerId", label: "Customer ID", table: true },
      { name: "startDate", label: "Start date", type: "date", table: true },
      { name: "endDate", label: "End date", type: "date", table: true },
      { name: "used", label: "Included visits used", type: "number", table: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Active", "Frozen", "Expired", "Cancelled"],
        table: true,
        badge: true,
      },
    ],
  },
  campaigns: {
    key: "campaigns",
    title: "Marketing Campaigns",
    subtitle: "WhatsApp, Instagram, SMS and email outreach performance.",
    idPrefix: "CP-",
    fields: [
      { name: "name", label: "Campaign name", table: true },
      {
        name: "channel",
        label: "Channel",
        type: "select",
        options: ["WhatsApp", "Instagram", "SMS", "Email"],
        table: true,
        badge: true,
      },
      { name: "segment", label: "Segment", table: true },
      { name: "audience", label: "Audience size", type: "number", table: true },
      { name: "sent", label: "Sent", type: "number", table: true },
      { name: "opened", label: "Opened", type: "number" },
      { name: "converted", label: "Converted", type: "number", table: true },
      { name: "budget", label: "Budget", type: "number", money: true },
      { name: "schedule", label: "Schedule" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Draft", "Scheduled", "Running", "Completed", "Paused"],
        table: true,
        badge: true,
      },
    ],
  },
  franchises: {
    key: "franchises",
    title: "Franchises",
    subtitle: "Outlet network, ownership, GSTIN and royalty terms.",
    idPrefix: "FR-",
    fields: [
      { name: "name", label: "Outlet name", table: true },
      {
        name: "type",
        label: "Type",
        type: "select",
        options: ["Company Owned", "Franchise"],
        table: true,
        badge: true,
      },
      { name: "city", label: "City", table: true },
      { name: "owner", label: "Owner / manager", table: true },
      { name: "phone", label: "Phone" },
      { name: "gstin", label: "GSTIN", table: true },
      { name: "royalty", label: "Royalty %", type: "number", table: true },
      { name: "goLive", label: "Go-live date", type: "date", table: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Active", "Onboarding", "Suspended"],
        table: true,
        badge: true,
      },
    ],
  },
  brandApps: {
    key: "brandApps",
    title: "White-Label Apps",
    subtitle: "Branded app and website publishing per outlet.",
    idPrefix: "BA-",
    fields: [
      { name: "outlet", label: "Outlet", type: "select", options: outlets, table: true },
      { name: "appName", label: "App name", table: true },
      { name: "primaryColor", label: "Brand colour", table: true },
      { name: "bundleId", label: "Bundle ID", table: true },
      { name: "platform", label: "Platform", type: "select", options: ["iOS + Android", "iOS", "Android"], table: true },
      { name: "version", label: "Version", table: true },
      { name: "website", label: "Website" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Draft", "In Review", "Live"],
        table: true,
        badge: true,
      },
    ],
  },
  users: {
    key: "users",
    title: "Users & Roles",
    subtitle: "Access control across HQ and outlets.",
    idPrefix: "U-",
    fields: [
      { name: "name", label: "Name", table: true },
      { name: "email", label: "Email", table: true },
      {
        name: "role",
        label: "Role",
        type: "select",
        options: workspaceRoleNames,
        table: true,
        badge: true,
      },
      { name: "outlet", label: "Outlet", type: "select", options: outlets, table: true },
      { name: "permissions", label: "Permissions", table: true, form: false },
      { name: "lastLogin", label: "Last login", table: true },
      { name: "status", label: "Status", type: "select", options: ["Active", "Suspended"], table: true, badge: true },
    ],
  },
  roles: {
    key: "roles",
    title: "Roles & permissions",
    subtitle: "Create roles and set view / edit access per screen. Seeded from the users you already have.",
    idPrefix: "RL-",
    fields: [
      { name: "name", label: "Role name", table: true },
      {
        name: "code",
        label: "Login type",
        type: "select",
        options: ["ADMIN", "STAFF", "STYLIST"],
        table: true,
        badge: true,
      },
      { name: "description", label: "Description", type: "textarea", table: true },
      { name: "builtIn", label: "Built-in", type: "select", options: ["Yes", "No"], table: true, form: false },
      { name: "view", label: "View screens", table: true, form: false },
      { name: "edit", label: "Edit screens", table: true, form: false },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Active", "Inactive"],
        table: true,
        badge: true,
      },
    ],
  },
} satisfies Record<string, ModuleDef>;

export const navSections: { label: string; items: { to: string; label: string; icon: string }[] }[] = [
  {
    label: "Overview",
    items: [{ to: "/dashboard", label: "Dashboard", icon: "LayoutDashboard" }],
  },
  {
    label: "Front desk",
    items: [
      { to: "/customers", label: "Customers", icon: "Users" },
      { to: "/appointments", label: "Appointments", icon: "CalendarDays" },
      { to: "/pos", label: "POS & Billing", icon: "Receipt" },
      { to: "/services", label: "Services", icon: "Scissors" },
      { to: "/feedback", label: "Feedback", icon: "MessageSquareHeart" },
    ],
  },
  {
    label: "Operations",
    items: [
      { to: "/inventory", label: "Inventory", icon: "Package" },
      { to: "/expenses", label: "Expenses", icon: "Wallet" },
    ],
  },
  {
    label: "People",
    items: [
      { to: "/staff", label: "Staff", icon: "IdCard" },
      { to: "/shifts", label: "Shifts", icon: "CalendarClock" },
      { to: "/attendance", label: "Attendance", icon: "Clock" },
      { to: "/leaves", label: "Leaves", icon: "PlaneTakeoff" },
      { to: "/payroll", label: "Payroll", icon: "BadgeIndianRupee" },
      { to: "/commissions", label: "Commissions", icon: "PiggyBank" },
    ],
  },
  {
    label: "Growth",
    items: [
      { to: "/loyalty", label: "Loyalty", icon: "Gift" },
      { to: "/offers", label: "Offers", icon: "TicketPercent" },
      { to: "/memberships", label: "Memberships", icon: "CreditCard" },
      { to: "/book", label: "Public booking site", icon: "Globe" },
    ],
  },
  {
    label: "CRM",
    items: [{ to: "/campaigns", label: "Campaigns", icon: "Megaphone" }],
  },
  {
    label: "Network",
    items: [
      { to: "/franchises", label: "Franchises", icon: "Store" },
      { to: "/brand-apps", label: "White-Label Apps", icon: "Smartphone" },
      { to: "/users", label: "Users", icon: "ShieldCheck" },
      { to: "/roles", label: "Roles & permissions", icon: "Lock" },
      { to: "/subscription", label: "Subscription", icon: "CreditCard" },
      { to: "/settings", label: "Settings", icon: "Settings" },
    ],
  },
];
